<?php

namespace PFE\V3\MobSurveyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnqueteRepository extends EntityRepository
{
}
