<?php

namespace PFE\V3\MobSurveyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository
{
    function myFindByDate($dateDebut, $dateFin)
    {
        return $this->findAll();

    }
}
