<?php

namespace PFE\V3\MobSurveyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuperviseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperviseurRepository extends EntityRepository
{
}
