jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        "FOS\UserBundle\Model\UserInterface": plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path:  fos_user_security_check
                default_target_path: ms_homepage
                always_use_default_target_path: true
                failure_path:   ms_login
            logout:
                path: fos_user_security_logout
                target: ms_homepage
            anonymous:  true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/PFE/V3/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/PFE/V3/rest/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/PFE/V3/security/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/PFE/V3/question/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/PFE/V3/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/PFE/V3/*, role: ROLE_ADMIN }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
